"""Single source of truth for top-level public exports."""

from __future__ import annotations

from typing import Final

TOP_LEVEL_EXPORTS: Final[dict[str, str]] = {
    "DirectLLMCall": "design_research_agents.agent:DirectLLMCall",
    "MultiStepAgent": "design_research_agents.agent:MultiStepAgent",
    "SkillsConfig": "design_research_agents.skills:SkillsConfig",
    "SeededRandomBaselineAgent": "design_research_agents.agent:SeededRandomBaselineAgent",
    "PromptWorkflowAgent": "design_research_agents.agent:PromptWorkflowAgent",
    "Toolbox": "design_research_agents.tools:Toolbox",
    "CallableToolConfig": "design_research_agents.tools:CallableToolConfig",
    "ScriptToolConfig": "design_research_agents.tools:ScriptToolConfig",
    "MCPServerConfig": "design_research_agents.tools:MCPServerConfig",
    "LogicStep": "design_research_agents._contracts:LogicStep",
    "WorkflowContext": "design_research_agents._contracts:WorkflowContext",
    "ToolStep": "design_research_agents._contracts:ToolStep",
    "DelegateStep": "design_research_agents._contracts:DelegateStep",
    "ModelStep": "design_research_agents._contracts:ModelStep",
    "DelegateBatchStep": "design_research_agents._contracts:DelegateBatchStep",
    "LoopStep": "design_research_agents._contracts:LoopStep",
    "MemoryReadStep": "design_research_agents._contracts:MemoryReadStep",
    "MemoryWriteStep": "design_research_agents._contracts:MemoryWriteStep",
    "ExecutionResult": "design_research_agents._contracts:ExecutionResult",
    "LLMRequest": "design_research_agents.llm:LLMRequest",
    "LLMMessage": "design_research_agents.llm:LLMMessage",
    "LLMResponse": "design_research_agents.llm:LLMResponse",
    "ToolResult": "design_research_agents.tools:ToolResult",
    "Workflow": "design_research_agents.workflow:Workflow",
    "CompiledExecution": "design_research_agents.workflow:CompiledExecution",
    "build_json_prompt_workflow": "design_research_agents.workflow:build_json_prompt_workflow",
    "TwoSpeakerConversationPattern": "design_research_agents.patterns:TwoSpeakerConversationPattern",
    "DebatePattern": "design_research_agents.patterns:DebatePattern",
    "PlanExecutePattern": "design_research_agents.patterns:PlanExecutePattern",
    "ProposeCriticPattern": "design_research_agents.patterns:ProposeCriticPattern",
    "ProposeCriticResult": "design_research_agents.patterns:ProposeCriticResult",
    "RalphLoopPattern": "design_research_agents.patterns:RalphLoopPattern",
    "NominalTeamPattern": "design_research_agents.patterns:NominalTeamPattern",
    "RouterDelegatePattern": "design_research_agents.patterns:RouterDelegatePattern",
    "RoundBasedCoordinationPattern": "design_research_agents.patterns:RoundBasedCoordinationPattern",
    "BlackboardPattern": "design_research_agents.patterns:BlackboardPattern",
    "TreeSearchPattern": "design_research_agents.patterns:TreeSearchPattern",
    "RAGPattern": "design_research_agents.patterns:RAGPattern",
    "ReinforcementLearningPattern": "design_research_agents.patterns:ReinforcementLearningPattern",
    "SimulatedAnnealingPattern": "design_research_agents.patterns:SimulatedAnnealingPattern",
    "AdaptiveSchedule": "design_research_agents._implementations._patterns:AdaptiveSchedule",
    "ExponentialSchedule": "design_research_agents._implementations._patterns:ExponentialSchedule",
    "LinearSchedule": "design_research_agents._implementations._patterns:LinearSchedule",
    "LogarithmicSchedule": "design_research_agents._implementations._patterns:LogarithmicSchedule",
    "TemperatureSchedule": "design_research_agents._implementations._patterns:TemperatureSchedule",
    "AnthropicServiceLLMClient": "design_research_agents.llm:AnthropicServiceLLMClient",
    "AzureOpenAIServiceLLMClient": "design_research_agents.llm:AzureOpenAIServiceLLMClient",
    "GeminiServiceLLMClient": "design_research_agents.llm:GeminiServiceLLMClient",
    "GroqServiceLLMClient": "design_research_agents.llm:GroqServiceLLMClient",
    "LlamaCppServerLLMClient": "design_research_agents.llm:LlamaCppServerLLMClient",
    "OpenAIServiceLLMClient": "design_research_agents.llm:OpenAIServiceLLMClient",
    "OpenAICompatibleHTTPLLMClient": "design_research_agents.llm:OpenAICompatibleHTTPLLMClient",
    "TransformersLocalLLMClient": "design_research_agents.llm:TransformersLocalLLMClient",
    "MLXLocalLLMClient": "design_research_agents.llm:MLXLocalLLMClient",
    "VLLMServerLLMClient": "design_research_agents.llm:VLLMServerLLMClient",
    "OllamaLLMClient": "design_research_agents.llm:OllamaLLMClient",
    "SGLangServerLLMClient": "design_research_agents.llm:SGLangServerLLMClient",
    "ModelCatalog": "design_research_agents.model_selection:ModelCatalog",
    "ModelFlight": "design_research_agents.model_selection:ModelFlight",
    "ModelFlightRegistry": "design_research_agents.model_selection:ModelFlightRegistry",
    "ModelSelector": "design_research_agents.model_selection:ModelSelector",
    "AgentExecutionEnvelope": "design_research_agents.study:AgentExecutionEnvelope",
    "AgentRunRequest": "design_research_agents.study:AgentRunRequest",
    "StudyCondition": "design_research_agents.study:StudyCondition",
    "execute_agent_request": "design_research_agents.study:execute_agent_request",
    "execute_agent_run": "design_research_agents.study:execute_agent_run",
    "normalize_agent_execution": "design_research_agents.study:normalize_agent_execution",
    "Tracer": "design_research_agents._tracing:Tracer",
}

TOP_LEVEL_SUBMODULES: Final[dict[str, str]] = {
    "integration": "design_research_agents.integration",
    "model_selection": "design_research_agents.model_selection",
    "study": "design_research_agents.study",
}

TOP_LEVEL_PUBLIC_API: Final[tuple[str, ...]] = (
    "__version__",
    *TOP_LEVEL_EXPORTS.keys(),
    *TOP_LEVEL_SUBMODULES.keys(),
)
