# Pre-commit configuration

default_stages: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: make-pre-commit
        name: make pre-commit
        entry: make pre-commit
        language: system
        pass_filenames: false