name: Examples

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  deterministic-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: make install-dev

      - name: Run full deterministic examples suite
        run: make examples-test
